def explain_compound(data):

    name = data["name"]
    formula = data["formula"]
    mw = data["molecular_weight"]

    groups = data.get("groups", [])

    text = f"{name.title()} is an organic compound with the molecular formula {formula}. "

    if groups:
        text += f"It contains the following functional groups: {', '.join(groups)}. "

    text += f"It has a molecular weight of {mw}. "

    text += (
        "This information is generated by ChemAI using chemical data "
        "and molecular analysis."
    )

    return text